/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.onlineinteract.workflow.domain.account.v2;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class AccountV2 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -9165770666614349930L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AccountV2\",\"namespace\":\"com.onlineinteract.workflow.domain.account.v2\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"type\",\"type\":\"string\"},{\"name\":\"openingBalance\",\"type\":\"string\"},{\"name\":\"savingsRate\",\"type\":\"string\"},{\"name\":\"enabled\",\"type\":\"boolean\"},{\"name\":\"addr1\",\"type\":\"string\"},{\"name\":\"addr2\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence type;
  @Deprecated public java.lang.CharSequence openingBalance;
  @Deprecated public java.lang.CharSequence savingsRate;
  @Deprecated public boolean enabled;
  @Deprecated public java.lang.CharSequence addr1;
  @Deprecated public java.lang.CharSequence addr2;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AccountV2() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param name The new value for name
   * @param type The new value for type
   * @param openingBalance The new value for openingBalance
   * @param savingsRate The new value for savingsRate
   * @param enabled The new value for enabled
   * @param addr1 The new value for addr1
   * @param addr2 The new value for addr2
   */
  public AccountV2(java.lang.CharSequence id, java.lang.CharSequence name, java.lang.CharSequence type, java.lang.CharSequence openingBalance, java.lang.CharSequence savingsRate, java.lang.Boolean enabled, java.lang.CharSequence addr1, java.lang.CharSequence addr2) {
    this.id = id;
    this.name = name;
    this.type = type;
    this.openingBalance = openingBalance;
    this.savingsRate = savingsRate;
    this.enabled = enabled;
    this.addr1 = addr1;
    this.addr2 = addr2;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return name;
    case 2: return type;
    case 3: return openingBalance;
    case 4: return savingsRate;
    case 5: return enabled;
    case 6: return addr1;
    case 7: return addr2;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: name = (java.lang.CharSequence)value$; break;
    case 2: type = (java.lang.CharSequence)value$; break;
    case 3: openingBalance = (java.lang.CharSequence)value$; break;
    case 4: savingsRate = (java.lang.CharSequence)value$; break;
    case 5: enabled = (java.lang.Boolean)value$; break;
    case 6: addr1 = (java.lang.CharSequence)value$; break;
    case 7: addr2 = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.CharSequence getType() {
    return type;
  }

  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.CharSequence value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'openingBalance' field.
   * @return The value of the 'openingBalance' field.
   */
  public java.lang.CharSequence getOpeningBalance() {
    return openingBalance;
  }

  /**
   * Sets the value of the 'openingBalance' field.
   * @param value the value to set.
   */
  public void setOpeningBalance(java.lang.CharSequence value) {
    this.openingBalance = value;
  }

  /**
   * Gets the value of the 'savingsRate' field.
   * @return The value of the 'savingsRate' field.
   */
  public java.lang.CharSequence getSavingsRate() {
    return savingsRate;
  }

  /**
   * Sets the value of the 'savingsRate' field.
   * @param value the value to set.
   */
  public void setSavingsRate(java.lang.CharSequence value) {
    this.savingsRate = value;
  }

  /**
   * Gets the value of the 'enabled' field.
   * @return The value of the 'enabled' field.
   */
  public java.lang.Boolean getEnabled() {
    return enabled;
  }

  /**
   * Sets the value of the 'enabled' field.
   * @param value the value to set.
   */
  public void setEnabled(java.lang.Boolean value) {
    this.enabled = value;
  }

  /**
   * Gets the value of the 'addr1' field.
   * @return The value of the 'addr1' field.
   */
  public java.lang.CharSequence getAddr1() {
    return addr1;
  }

  /**
   * Sets the value of the 'addr1' field.
   * @param value the value to set.
   */
  public void setAddr1(java.lang.CharSequence value) {
    this.addr1 = value;
  }

  /**
   * Gets the value of the 'addr2' field.
   * @return The value of the 'addr2' field.
   */
  public java.lang.CharSequence getAddr2() {
    return addr2;
  }

  /**
   * Sets the value of the 'addr2' field.
   * @param value the value to set.
   */
  public void setAddr2(java.lang.CharSequence value) {
    this.addr2 = value;
  }

  /**
   * Creates a new AccountV2 RecordBuilder.
   * @return A new AccountV2 RecordBuilder
   */
  public static com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder newBuilder() {
    return new com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder();
  }

  /**
   * Creates a new AccountV2 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AccountV2 RecordBuilder
   */
  public static com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder newBuilder(com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder other) {
    return new com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder(other);
  }

  /**
   * Creates a new AccountV2 RecordBuilder by copying an existing AccountV2 instance.
   * @param other The existing instance to copy.
   * @return A new AccountV2 RecordBuilder
   */
  public static com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder newBuilder(com.onlineinteract.workflow.domain.account.v2.AccountV2 other) {
    return new com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder(other);
  }

  /**
   * RecordBuilder for AccountV2 instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AccountV2>
    implements org.apache.avro.data.RecordBuilder<AccountV2> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence name;
    private java.lang.CharSequence type;
    private java.lang.CharSequence openingBalance;
    private java.lang.CharSequence savingsRate;
    private boolean enabled;
    private java.lang.CharSequence addr1;
    private java.lang.CharSequence addr2;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.type)) {
        this.type = data().deepCopy(fields()[2].schema(), other.type);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.openingBalance)) {
        this.openingBalance = data().deepCopy(fields()[3].schema(), other.openingBalance);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.savingsRate)) {
        this.savingsRate = data().deepCopy(fields()[4].schema(), other.savingsRate);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.enabled)) {
        this.enabled = data().deepCopy(fields()[5].schema(), other.enabled);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.addr1)) {
        this.addr1 = data().deepCopy(fields()[6].schema(), other.addr1);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.addr2)) {
        this.addr2 = data().deepCopy(fields()[7].schema(), other.addr2);
        fieldSetFlags()[7] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing AccountV2 instance
     * @param other The existing instance to copy.
     */
    private Builder(com.onlineinteract.workflow.domain.account.v2.AccountV2 other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.name)) {
        this.name = data().deepCopy(fields()[1].schema(), other.name);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.type)) {
        this.type = data().deepCopy(fields()[2].schema(), other.type);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.openingBalance)) {
        this.openingBalance = data().deepCopy(fields()[3].schema(), other.openingBalance);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.savingsRate)) {
        this.savingsRate = data().deepCopy(fields()[4].schema(), other.savingsRate);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.enabled)) {
        this.enabled = data().deepCopy(fields()[5].schema(), other.enabled);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.addr1)) {
        this.addr1 = data().deepCopy(fields()[6].schema(), other.addr1);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.addr2)) {
        this.addr2 = data().deepCopy(fields()[7].schema(), other.addr2);
        fieldSetFlags()[7] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder setName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.name = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder clearName() {
      name = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.CharSequence getType() {
      return type;
    }

    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder setType(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.type = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder clearType() {
      type = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'openingBalance' field.
      * @return The value.
      */
    public java.lang.CharSequence getOpeningBalance() {
      return openingBalance;
    }

    /**
      * Sets the value of the 'openingBalance' field.
      * @param value The value of 'openingBalance'.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder setOpeningBalance(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.openingBalance = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'openingBalance' field has been set.
      * @return True if the 'openingBalance' field has been set, false otherwise.
      */
    public boolean hasOpeningBalance() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'openingBalance' field.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder clearOpeningBalance() {
      openingBalance = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'savingsRate' field.
      * @return The value.
      */
    public java.lang.CharSequence getSavingsRate() {
      return savingsRate;
    }

    /**
      * Sets the value of the 'savingsRate' field.
      * @param value The value of 'savingsRate'.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder setSavingsRate(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.savingsRate = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'savingsRate' field has been set.
      * @return True if the 'savingsRate' field has been set, false otherwise.
      */
    public boolean hasSavingsRate() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'savingsRate' field.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder clearSavingsRate() {
      savingsRate = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'enabled' field.
      * @return The value.
      */
    public java.lang.Boolean getEnabled() {
      return enabled;
    }

    /**
      * Sets the value of the 'enabled' field.
      * @param value The value of 'enabled'.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder setEnabled(boolean value) {
      validate(fields()[5], value);
      this.enabled = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'enabled' field has been set.
      * @return True if the 'enabled' field has been set, false otherwise.
      */
    public boolean hasEnabled() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'enabled' field.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder clearEnabled() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'addr1' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddr1() {
      return addr1;
    }

    /**
      * Sets the value of the 'addr1' field.
      * @param value The value of 'addr1'.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder setAddr1(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.addr1 = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'addr1' field has been set.
      * @return True if the 'addr1' field has been set, false otherwise.
      */
    public boolean hasAddr1() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'addr1' field.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder clearAddr1() {
      addr1 = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'addr2' field.
      * @return The value.
      */
    public java.lang.CharSequence getAddr2() {
      return addr2;
    }

    /**
      * Sets the value of the 'addr2' field.
      * @param value The value of 'addr2'.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder setAddr2(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.addr2 = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'addr2' field has been set.
      * @return True if the 'addr2' field has been set, false otherwise.
      */
    public boolean hasAddr2() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'addr2' field.
      * @return This builder.
      */
    public com.onlineinteract.workflow.domain.account.v2.AccountV2.Builder clearAddr2() {
      addr2 = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    @Override
    public AccountV2 build() {
      try {
        AccountV2 record = new AccountV2();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.name = fieldSetFlags()[1] ? this.name : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.type = fieldSetFlags()[2] ? this.type : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.openingBalance = fieldSetFlags()[3] ? this.openingBalance : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.savingsRate = fieldSetFlags()[4] ? this.savingsRate : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.enabled = fieldSetFlags()[5] ? this.enabled : (java.lang.Boolean) defaultValue(fields()[5]);
        record.addr1 = fieldSetFlags()[6] ? this.addr1 : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.addr2 = fieldSetFlags()[7] ? this.addr2 : (java.lang.CharSequence) defaultValue(fields()[7]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
